export const FIRECRAWL_EXTRACT_SCHEMA = {
  type: "object",
  properties: {
    name: { type: "string", description: "Product name or title" },
    price: { type: "string", description: "Current selling price" },
    original_price: {
      type: "string",
      description: "Original price before discount",
    },
    currency: { type: "string", description: "Currency code, e.g. USD, EUR" },
    brand: { type: "string", description: "Brand or manufacturer" },
    image_url: { type: "string", description: "Main product image URL" },
    description: { type: "string", description: "Short product description" },
    options: {
      type: "array",
      description:
        "ALL product variant option groups (Color, Size, Style, Material, etc.)",
      items: {
        type: "object",
        properties: {
          name: { type: "string" },
          values: { type: "array", items: { type: "string" } },
        },
      },
    },
    variant_urls: {
      type: "array",
      description:
        "URLs for other variants of this same product (color swatches, style links, etc.)",
      items: { type: "string" },
    },
  },
} as const;

export const FIRECRAWL_EXTRACT_PROMPT =
  "Extract all product details exhaustively. Include EVERY variant group visible " +
  "on the page (Color swatches, Size buttons, Style selectors, etc.). For variant_urls, " +
  "include the href of every color swatch or variant link that loads a different variant. " +
  "If the page shows both subscription/autoship and one-time purchase prices, " +
  "extract the ONE-TIME (non-subscription) price as the main price. " +
  "If multiple prices appear (e.g. sale vs original), extract the current selling price as price " +
  "and the original/compare-at price as original_price.";

export const MAX_VARIANT_EXTRACT = 20;
export const CRAWL_PAGE_LIMIT = 25;
export const VARIANT_EXTRACT_CONCURRENCY = 5;
export const FIRECRAWL_POLL_INTERVAL_MS = 2000;

// ---- 404 / Discontinued detection ----

export class ProductNotFoundError extends Error {
  constructor(reason: string) {
    super(reason);
    this.name = "ProductNotFoundError";
  }
}

export class ProductBlockedError extends Error {
  constructor(reason: string) {
    super(reason);
    this.name = "ProductBlockedError";
  }
}

/** Content patterns that indicate a product page is 404 / discontinued / removed. */
export const NOT_FOUND_PATTERNS = [
  "this product is no longer available",
  "this item is no longer available",
  "product not found",
  "page not found",
  "item not found",
  "this page doesn't exist",
  "this page does not exist",
  "we couldn't find that page",
  "we could not find that page",
  "has been discontinued",
  "has been removed",
  "is no longer sold",
  "no longer in stock",
  "this product has been deleted",
  "sorry, this product is unavailable",
  "sorry, this item is unavailable",
  "the page you're looking for can't be found",
  "the page you are looking for cannot be found",
  "404 error",
  "404 not found",
  "item is currently unavailable and cannot be purchased",
  "we can't find the page you're looking for",
  "oops! that page can't be found",
  "this listing has ended",
  "this listing is no longer available",
];

// ---- HTML boilerplate stripping for smarter truncation ----

/** Selectors to try (in order) for main product content extraction. */
export const MAIN_CONTENT_SELECTORS = [
  "[itemtype*='schema.org/Product']",
  "[itemtype*='Product']",
  "main",
  "[role='main']",
  "#main-content",
  "#main",
  ".product-detail",
  ".product-page",
  "[data-product]",
  "#product",
  ".pdp-main",
  "#product-content",
  ".product-main",
  "[data-component='ProductDetail']",
  "article.product",
  ".pdp-container",
  ".product-details",
  ".product-info",
  "#pdp",
  "[data-testid='product-detail']",
  "[data-testid='pdp']",
  ".product-overview",
];

/** Boilerplate elements to strip before markdown conversion. */
export const BOILERPLATE_SELECTORS = [
  "header", "footer", "nav", "aside",
  ".navbar", "#header", ".footer", "#footer",
  ".sidebar", "#sidebar",
  ".modal", ".popup", ".overlay",
  ".ad", ".ads", ".advert",
  ".social", ".social-links",
  ".menu", ".navigation", "#nav",
  ".breadcrumbs",
  ".cookie",
  "[role='banner']", "[role='navigation']", "[role='contentinfo']",
  ".recently-viewed", ".recommendations", ".also-bought",
  ".newsletter", "#newsletter",
];

export const BLOCKED_PATTERNS = [
  // Cloudflare
  "just a moment", "checking your browser", "ray id", "cloudflare",
  "cf-browser-verification", "challenge-platform",
  "cf_chl_opt", "managed_checking_msg", "challenge-error-title",
  // Akamai / PerimeterX / DataDome
  "access denied", "reference #", "automated access",
  "request could not be satisfied", "generated by wordfence",
  "px-captcha", "datadome",
  // Generic bot detection
  "enable javascript", "please verify you are a human",
  "captcha", "bot detection", "are you a robot",
  "browser verification", "security check", "human verification",
  // Incapsula / Imperva
  "incapsula incident", "request unsuccessful",
  // DistilNetworks
  "pardon our interruption",
];

/**
 * Classify page content for bot-blocking or not-found signals.
 * Returns "blocked", "not_found", or null if content looks valid.
 *
 * `maxLenForCheck` caps the content length threshold for pattern matching —
 * very long pages are unlikely to be challenge/error pages.
 */
export function classifyContent(
  content: string,
  maxLenForCheck: number,
): "blocked" | "not_found" | null {
  if (content.length === 0) return null;
  const lower = content.toLowerCase();

  // Blocked patterns take priority over not-found to avoid false 404s
  if (content.length < maxLenForCheck && BLOCKED_PATTERNS.some((p) => lower.includes(p))) {
    return "blocked";
  }
  if (content.length < maxLenForCheck && NOT_FOUND_PATTERNS.some((p) => lower.includes(p))) {
    return "not_found";
  }
  return null;
}
